### ISSUE TITLE
Kind request to include Java8 unlimited JCE policy extension into openhab docker image

### ISSUE THREAD

**Issue by doc1138** [openhab/openhab-docker#118]
Hi there,
first of all thank you for providing an official openhab docker image!!!
I experience an issue with the binding for my heating (Buderus KM200) that requires the Java8 extension for unlimited JCE policy to allow longer hashes for password strings to be able to read and decode the data coming from the gateway. Probably this issue does not only affect me with the KM200 binding but also other bindings that use today resp. will use in the future longer hash strings for authentication as supported with the standard version of Java.
Even though JCE is included in the docker image it does not work correctly. Please find below the error I get in the openhab.log:

> 22:54:07.169 [INFO ] [.binding.km200.internal.KM200Binding] - Update KM200 Binding configuration, it takes a minute....
> 2017-10-30 22:54:07.178 [INFO ] [.binding.km200.internal.KM200Binding] - Starting communication test..
> 2017-10-30 22:54:07.446 [INFO ] [.binding.km200.internal.KM200Binding] - Received data..
> 2017-10-30 22:54:07.460 [ERROR] [hab.binding.km200.internal.KM200Comm] - Exception on encoding: {}
> java.security.InvalidKeyException: Illegal key size or default parameters
> 	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)[:1.8.0_144]
> 	at javax.crypto.Cipher.implInit(Cipher.java:801)[:1.8.0_144]
> 	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)[:1.8.0_144]
> 	at javax.crypto.Cipher.init(Cipher.java:1249)[:1.8.0_144]
> 	at javax.crypto.Cipher.init(Cipher.java:1186)[:1.8.0_144]
> 	at org.openhab.binding.km200.internal.KM200Comm.decodeMessage(KM200Comm.java:260)[183:org.openhab.binding.km200:1.10.0]
> 	at org.openhab.binding.km200.internal.KM200Binding.updated(KM200Binding.java:161)[183:org.openhab.binding.km200:1.10.0]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
> 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
> 2017-10-30 22:54:07.466 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.osgi.service.event.EventHandler, id=292, bundle=183/mvn:org.openhab.binding/org.openhab.binding.km200/1.10.0]: Unexpected problem updating configuration org.openhab.km200
> java.lang.RuntimeException: Decoding of the KM200 message is not possible!
> 	at org.openhab.binding.km200.internal.KM200Binding.updated(KM200Binding.java:163)[183:org.openhab.binding.km200:1.10.0]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
> 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
> 

I did some research what is needed for JCE and found the following to JAR files need to be installed in the docker image. The files are called **local_policy.jar** and **US_export_policy.jar** and they are in the image as shown below:

> root@openhab-openhab220:/usr/lib/java-8/jre/lib/security# ls -l
> total 236
> -rw-rw-r-- 1 31450 31450 1273 Jul 26 14:24 blacklisted.certs
> -rw-rw-r-- 1 31450 31450 186962 Jul 26 14:24 cacerts
> -rw-rw-r-- 1 31450 31450 2466 Jul 26 14:24 java.policy
> -rw-rw-r-- 1 31450 31450 34688 Jul 26 14:24 java.security
> -rw-rw-r-- 1 31450 31450 1040 Jul 26 14:24 local_policy.jar
> -rw-rw-r-- 1 31450 31450 620 Jul 26 14:24 US_export_policy.jar
> root@openhab-openhab220:/usr/lib/java-8/jre/lib/security#

I don't get errors and it works with the wetware/openhab docker image which uses OpenJDK 1.8.0.45 with JCE and the JDK used in your official openhab image is 1.8.0_144 and has also the JCE files. Hence there must be the difference in the Java versions and/or probably in the Java default configuration.

I would prefer much more to use your official image as some cloned one.
Hence I kindly ask you to consider my issue!

**Comment by doc1138** [comment]
Hi there,
I did some more research and found that the JCE policy files are installed in the docker image. The are called **local_policy.jar** and **US_export_policy.jar** as shown below:

`root@openhab-openhab220:/usr/lib/java-8/jre/lib/security# ls -l   
total 236
-rw-rw-r-- 1 31450 31450   1273 Jul 26 14:24 blacklisted.certs
-rw-rw-r-- 1 31450 31450 186962 Jul 26 14:24 cacerts
-rw-rw-r-- 1 31450 31450   2466 Jul 26 14:24 java.policy
-rw-rw-r-- 1 31450 31450  34688 Jul 26 14:24 java.security
-rw-rw-r-- 1 31450 31450   1040 Jul 26 14:24 local_policy.jar
-rw-rw-r-- 1 31450 31450    620 Jul 26 14:24 US_export_policy.jar
root@openhab-openhab220:/usr/lib/java-8/jre/lib/security# 
`
It works with the wetware/openhab docker image which uses OpenJDK 1.8.0.45 but the JDK used in the original openhab image is 1.8.0_144 and has the JCE files. Hence there must be the difference in the Java versions and probably Java default configuration.

I kindly ask you to fix this :-)

**Comment by doc1138** [comment]
I tried a lot an finally found the solution on my own. Eventhough the files from the Java Cryptographic Extension might exist in the container. They are wrong. I explained everything very detailed in the following thread how to make a workaround for the existing docker container.

[https://community.openhab.org/t/java-encoding-decoding-error-with-km200-binding-although-java8-jce-is-installed/35676](url)

For the future it would be kind to consider to integrate the patched files directly into the container. The can be downloaded here:

[http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html](url)

Thank you!!!

**Comment by cniweb** [comment]
We don´t use the oracle jdk, we use zulu zdk-8 for debian and openjdk8 for alpine.
Can we use the JCE Policy files with other JDKs except those from Oracle?

**Comment by doc1138** [comment]
Hi, I am currently using your official 2.2.0-snapshot-amd64-debian openHAB image from docker hub:

[https://hub.docker.com/r/openhab/openhab/](https://hub.docker.com/r/openhab/openhab/)

and I patched it with the JCE files from Oracle, hence it obviously works with zdk-8 for debian :-)
I can also try out the alpine image on the weekend to confirm that it works with alpine as well but I would assume that it should work like it does with debian. I will let you know ...

And as a little off-topic request would you mind to include the "vim" package" in your docker image as for a UNIX geek like me it is the no. 1 editor :-) ... Cheers

**Comment by doc1138** [comment]
Hi cniweb,
I tested the alpine docker image: 2.2.0-snapshot-amd64-alpine and it works out of the box without replacing the JCE policy files but the charts are not working anymore (see errors in openhab.log):

**No more charts are created - which worries as this works perfectly with the debian image ???**

`2017-11-03 14:36:40.720 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /chart
java.lang.NullPointerException: null
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) [?:?]
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) [?:?]
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107) [?:?]
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774) [?:?]
        at sun.font.SunFontManager$2.run(SunFontManager.java:431) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.font.SunFontManager.<init>(SunFontManager.java:376) [?:?]
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35) [?:?]
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57) [?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:?]
        at java.lang.Class.newInstance(Class.java:442) [?:?]
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) [?:?]
        at java.awt.Font.getFont2D(Font.java:491) [?:?]
        at java.awt.Font.defaultLineMetrics(Font.java:2176) [?:?]
        at java.awt.Font.getLineMetrics(Font.java:2283) [?:?]
        at java.awt.font.TextLayout.fastInit(TextLayout.java:598) [?:?]
        at java.awt.font.TextLayout.<init>(TextLayout.java:393) [?:?]
        at org.knowm.xchart.internal.chartpart.Legend.getSeriesTextBounds(Legend.java:302) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.knowm.xchart.internal.chartpart.Legend.determineLegendBoxSize(Legend.java:84) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.knowm.xchart.internal.chartpart.ChartPainter.paint(ChartPainter.java:112) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.knowm.xchart.Chart.paint(Chart.java:102) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.eclipse.smarthome.ui.internal.chart.defaultchartprovider.DefaultChartProvider.createChart(DefaultChartProvider.java:273) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.eclipse.smarthome.ui.internal.chart.ChartServlet.doGet(ChartServlet.java:279) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [30:javax.servlet-api:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [30:javax.servlet-api:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [85:org.eclipse.jetty.servlet:9.3.14.v20161028]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [85:org.eclipse.jetty.servlet:9.3.14.v20161028]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [82:org.eclipse.jetty.security:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:284) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [85:org.eclipse.jetty.servlet:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [76:org.eclipse.jetty.io:9.3.14.v20161028]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [76:org.eclipse.jetty.io:9.3.14.v20161028]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [76:org.eclipse.jetty.io:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2017-11-03 14:36:40.724 [WARN ] [org.eclipse.jetty.server.HttpChannel] - //richcube:32775/chart?groups=gTempBad&period=h&service=mysql&theme=bright&t=1509719800082
java.lang.NullPointerException: null
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) [?:?]
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) [?:?]
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107) [?:?]
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774) [?:?]
        at sun.font.SunFontManager$2.run(SunFontManager.java:431) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.font.SunFontManager.<init>(SunFontManager.java:376) [?:?]
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35) [?:?]
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57) [?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:?]
        at java.lang.Class.newInstance(Class.java:442) [?:?]
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) [?:?]
        at java.awt.Font.getFont2D(Font.java:491) [?:?]
        at java.awt.Font.defaultLineMetrics(Font.java:2176) [?:?]
        at java.awt.Font.getLineMetrics(Font.java:2283) [?:?]
        at java.awt.font.TextLayout.fastInit(TextLayout.java:598) [?:?]
        at java.awt.font.TextLayout.<init>(TextLayout.java:393) [?:?]
        at org.knowm.xchart.internal.chartpart.Legend.getSeriesTextBounds(Legend.java:302) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.knowm.xchart.internal.chartpart.Legend.determineLegendBoxSize(Legend.java:84) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.knowm.xchart.internal.chartpart.ChartPainter.paint(ChartPainter.java:112) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.knowm.xchart.Chart.paint(Chart.java:102) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.eclipse.smarthome.ui.internal.chart.defaultchartprovider.DefaultChartProvider.createChart(DefaultChartProvider.java:273) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at org.eclipse.smarthome.ui.internal.chart.ChartServlet.doGet(ChartServlet.java:279) [137:org.eclipse.smarthome.ui:0.9.0.201710240931]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [30:javax.servlet-api:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [30:javax.servlet-api:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [85:org.eclipse.jetty.servlet:9.3.14.v20161028]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [85:org.eclipse.jetty.servlet:9.3.14.v20161028]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [82:org.eclipse.jetty.security:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:284) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [85:org.eclipse.jetty.servlet:9.3.14.v20161028]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [84:org.eclipse.jetty.server:9.3.14.v20161028]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [76:org.eclipse.jetty.io:9.3.14.v20161028]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [76:org.eclipse.jetty.io:9.3.14.v20161028]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [76:org.eclipse.jetty.io:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [87:org.eclipse.jetty.util:9.3.14.v20161028]
        at java.lang.Thread.run(Thread.java:748) [?:?]
`

**Conclusion:**
1) Alpine Image works without Java JCE patching but has issues with "charts".
2) Debian Image works only with Java JCE patching but has no issues with "charts".

I do not know whether the charts problem lies in my configuration. I will try to find out but you know now that the JCE issues are only in the zulu zdk-8.

**Comment by cniweb** [comment]
@doc1138 Can you open a new isue for the font / chats problem with alpine and yout vim pacage request?
I will biuld a new image with the JCE patch in the debian images.

**Comment by smerschjohann** [comment]
You can download the JCE policy from zulu: https://cdn.azul.com/zcek/bin/ZuluJCEPolicies.zip

We could add it by these lines:

```
RUN cd /tmp \
    && wget https://cdn.azul.com/zcek/bin/ZuluJCEPolicies.zip \
    && unzip -jo -d ${JAVA_HOME}/jre/lib/security /tmp/ZuluJCEPolicies.zip \
    && rm /tmp/ZuluJCEPolicies.zip
```

I can do a PR if wanted

**Comment by cniweb** [comment]
That sounds good, I'll include it

**Comment by cniweb** [comment]
The file ZuluJCEPolicies.zip is only 12kB in size. This may allow you to add an environment variable that the user sets to accept the Zulu conditions. When the image is started, the entrepoint script checks the variable and downloads and extracts the zip file as needed.

**Comment by doc1138** [comment]
Does this mean that you don't want to include it in your image?
That works for me but let me put it the other way round: As this is only 12kB you might want to consider to attract new less experienced users/adopters for openHAB and hence you should care about offering at least a predictable, identical behaviour of both images. Your two images behave differently and it took me two days to find out and solve it!
I am fine now ... I am already mounting the files from outside the image and I will be able to port this workaround over and over to the next container releases.
I understand your objective to keep the image as lean as possible but as Java is the core of OpenHAB you need to provide all the required functionality around Java in all images the same way! Today only my binding might be affected but as an encrypted connection to a device is key feature for a secure communication the JCE issue will hit other bindings as well.

**Comment by wborn** [comment]
> I understand your objective to keep the image as lean as possible

The objective is to have an image that legal to use in any country of  the world. See also the discussion in the PR: https://github.com/openhab/openhab-docker/pull/138#issuecomment-353203001 . In some countries of the world you can get locked up in jail just because you have downloaded strong cryptology algorithms.

**Comment by doc1138** [comment]
Oops ... I apologize. 😳  ... I did not look up the other thread. Just looked through this one.
Ok, this is a strong argument that I obviously cannot beat 😄. Good that I have documented how to add the JCE in the forum:
https://community.openhab.org/t/java-encoding-decoding-error-with-km200-binding-although-java8-jce-is-installed/35676

 ... hopefully this changes in the future ... so I consider the request to be closed ;-)

**Comment by smerschjohann** [comment]
The idea is here to have a environment variable that installs unlimited jce if this environment variable is set.

To your other case: You can always build your own docker image based on this image. I made my own image which has unlimited JCE + the jython environment for JSR223: https://github.com/smerschjohann/docker-oh2-jsr223

**Comment by doc1138** [comment]
I kindly appreciate your hint. I am just getting used to docker and did not yet try to build my own image but this should be worth to start trying :-) Currently I am trying to migrate from my last 2.2 snapshot container to the final release as I saw that there are now the snapshots for 2.3 available :-)
... need some time to adjust :-)

**Comment by cniweb** [comment]
Yes, would implement the JCE-Download feature via environment variable.
