### ISSUE TITLE
Charts not working in alpine image but working in debian image (2.2.0-snapshot-amd64)

### ISSUE THREAD

**Issue by doc1138** [openhab/openhab-docker#122]
Hi cniweb,
the docker image "2.2.0-snapshot-amd64-debian" works with my configuration files but when using the corresponding alpine image (2.2.0-snapshot-amd64-alpine) the charts are not working anymore and I get the following error openhab.log when calling the charts page of my sitemap in BASIC UI:

`
2017-11-03 14:36:40.720 [WARN ] [eclipse.jetty.servlet.ServletHandler] - /chart java.lang.NullPointerException: null at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) [?:?] at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) [?:?] at sun.awt.FontConfiguration.init(FontConfiguration.java:107) [?:?] at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774) [?:?] at sun.font.SunFontManager$2.run(SunFontManager.java:431) [?:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:?] at sun.font.SunFontManager.<init>(SunFontManager.java:376) [?:?] at sun.awt.FcFontManager.<init>(FcFontManager.java:35) [?:?] at sun.awt.X11FontManager.<init>(X11FontManager.java:57) [?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?] at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:?] at java.lang.Class.newInstance(Class.java:442) [?:?] at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) [?:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:?] at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) [?:?] at java.awt.Font.getFont2D(Font.java:491) [?:?] at java.awt.Font.defaultLineMetrics(Font.java:2176) [?:?] at java.awt.Font.getLineMetrics(Font.java:2283) [?:?] at java.awt.font.TextLayout.fastInit(TextLayout.java:598) [?:?] at java.awt.font.TextLayout.<init>(TextLayout.java:393) [?:?] at org.knowm.xchart.internal.chartpart.Legend.getSeriesTextBounds(Legend.java:302) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.knowm.xchart.internal.chartpart.Legend.determineLegendBoxSize(Legend.java:84) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.knowm.xchart.internal.chartpart.ChartPainter.paint(ChartPainter.java:112) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.knowm.xchart.Chart.paint(Chart.java:102) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.eclipse.smarthome.ui.internal.chart.defaultchartprovider.DefaultChartProvider.createChart(DefaultChartProvider.java:273) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.eclipse.smarthome.ui.internal.chart.ChartServlet.doGet(ChartServlet.java:279) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [30:javax.servlet-api:3.1.0] at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [30:javax.servlet-api:3.1.0] at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [85:org.eclipse.jetty.servlet:9.3.14.v20161028] at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [85:org.eclipse.jetty.servlet:9.3.14.v20161028] at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [82:org.eclipse.jetty.security:9.3.14.v20161028] at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:284) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6] at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [85:org.eclipse.jetty.servlet:9.3.14.v20161028] at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6] at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.Server.handle(Server.java:534) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [76:org.eclipse.jetty.io:9.3.14.v20161028] at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [76:org.eclipse.jetty.io:9.3.14.v20161028] at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [76:org.eclipse.jetty.io:9.3.14.v20161028] at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [87:org.eclipse.jetty.util:9.3.14.v20161028] at java.lang.Thread.run(Thread.java:748) [?:?] 2017-11-03 14:36:40.724 [WARN ] [org.eclipse.jetty.server.HttpChannel] - //richcube:32775/chart?groups=gTempBad&period=h&service=mysql&theme=bright&t=1509719800082 java.lang.NullPointerException: null at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) [?:?] at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) [?:?] at sun.awt.FontConfiguration.init(FontConfiguration.java:107) [?:?] at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774) [?:?] at sun.font.SunFontManager$2.run(SunFontManager.java:431) [?:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:?] at sun.font.SunFontManager.<init>(SunFontManager.java:376) [?:?] at sun.awt.FcFontManager.<init>(FcFontManager.java:35) [?:?] at sun.awt.X11FontManager.<init>(X11FontManager.java:57) [?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?] at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:?] at java.lang.Class.newInstance(Class.java:442) [?:?] at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83) [?:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:?] at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) [?:?] at java.awt.Font.getFont2D(Font.java:491) [?:?] at java.awt.Font.defaultLineMetrics(Font.java:2176) [?:?] at java.awt.Font.getLineMetrics(Font.java:2283) [?:?] at java.awt.font.TextLayout.fastInit(TextLayout.java:598) [?:?] at java.awt.font.TextLayout.<init>(TextLayout.java:393) [?:?] at org.knowm.xchart.internal.chartpart.Legend.getSeriesTextBounds(Legend.java:302) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.knowm.xchart.internal.chartpart.Legend.determineLegendBoxSize(Legend.java:84) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.knowm.xchart.internal.chartpart.ChartPainter.paint(ChartPainter.java:112) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.knowm.xchart.Chart.paint(Chart.java:102) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.eclipse.smarthome.ui.internal.chart.defaultchartprovider.DefaultChartProvider.createChart(DefaultChartProvider.java:273) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at org.eclipse.smarthome.ui.internal.chart.ChartServlet.doGet(ChartServlet.java:279) [137:org.eclipse.smarthome.ui:0.9.0.201710240931] at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [30:javax.servlet-api:3.1.0] at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [30:javax.servlet-api:3.1.0] at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [85:org.eclipse.jetty.servlet:9.3.14.v20161028] at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [85:org.eclipse.jetty.servlet:9.3.14.v20161028] at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [82:org.eclipse.jetty.security:9.3.14.v20161028] at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:284) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6] at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [85:org.eclipse.jetty.servlet:9.3.14.v20161028] at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [171:org.ops4j.pax.web.pax-web-jetty:6.0.6] at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.Server.handle(Server.java:534) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [84:org.eclipse.jetty.server:9.3.14.v20161028] at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [76:org.eclipse.jetty.io:9.3.14.v20161028] at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [76:org.eclipse.jetty.io:9.3.14.v20161028] at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [76:org.eclipse.jetty.io:9.3.14.v20161028] at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [87:org.eclipse.jetty.util:9.3.14.v20161028] at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [87:org.eclipse.jetty.util:9.3.14.v20161028] at java.lang.Thread.run(Thread.java:748) [?:?]
`

Seems to be a difference in the two JAVA distributions.

Opening this issue as requested. Let me know if I shall provide any additional debug information ...

**Comment by cniweb** [comment]
@doc1138  you can try now:
https://hub.docker.com/r/openhab/openhab/tags/

**Comment by doc1138** [comment]
Thank you very much. Awesome how quick you worked on this!!! I will try during the weekend and give feedback then!
