### ISSUE TITLE
Installation of binding fails

### ISSUE THREAD

**Issue by ccbur** [openhab/openhab-docker#355]
## Summary
The docker images from https://hub.docker.com/r/openhab/openhab/ can no longer download bindings from openhab.jfrog.io.

See:
[Thread 1](https://community.openhab.org/t/openhab-2-5-12-downloading-of-mvn-mysql-mysql-connector-java-8-0-13-fails/118796)
[Thread 2](https://community.openhab.org/t/urgent-help-openhab-in-docker-container-fails-installing-bindings-but-internet-connection-works/118806/6
)
## Expected Behavior
Starting a docker image with a binding configured in addons.cfg should work.

## Current Behavior
The following exception is thrown:

```
org.apache.karaf.features.internal.util.MultiException: Error:
Error downloading mvn:mysql/mysql-connector-java/8.0.13
at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.(MavenDownloadManager.java:91)
at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Suppressed: java.io.IOException: Error downloading mvn:mysql/mysql-connector-java/8.0.13
at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
… 3 more
Caused by: java.io.IOException: Error resolving artifact mysql:mysql-connector-java:jar:8.0.13: [Could not find artifact mysql:mysql-connector-java:jar:8.0.13 in openhab (https://openhab.jfrog.io/openhab/libs-release/)]
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
… 7 more
Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact mysql:mysql-connector-java:jar:8.0.13 in openhab (https://openhab.jfrog.io/openhab/libs-release/)
at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
… 12 more
Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact mysql:mysql-connector-java:jar:8.0.13
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
… 12 more
17:36:15.138 [ERROR] [core.karaf.internal.FeatureInstaller] [] - Failed installing ‘openhab-binding-http1, openhab-persistence-jdbc-mysql, openhab-transformation-javascript, openhab-persistence-influxdb, openhab-binding-novelanheatpump1, openhab-binding-weather1, openhab-misc-ruleengine, openhab-persistence-rrd4j, openhab-ui-basic, openhab-binding-onewire, openhab-binding-astro, openhab-binding-kostalinverter, openhab-binding-squeezebox, openhab-binding-knx, openhab-ui-paper’: Error:
Error downloading mvn:mysql/mysql-connector-java/8.0.13
```

## Possible Solution
Missing or wrong cert in keystore?

## Steps to Reproduce
1. Start openhab container
2. Install any binding

## Context
I can no longer use openHAB. Other users are effected, too.

## Your Environment
Docker container

### Image
*Images used:
openhab/openhab:2.5.5-debian
openhab/openhab:2.5.11-debian
openhab/openhab:2.5.12-debian
openhab/openhab:3.1.0-debian
*bindings: jdbc-mysql, but also every other binding

### Docker Host
* Operating System: self made Debian Buster
* Docker Version: 18.09.7
* Kernel Version: 4.14.2
* Architecture: armv7l

### Configuration
addons.cfg:
```
# The installation package of this openHAB instance
# Note: This is only regarded at the VERY FIRST START of openHAB
# Note: If you want to specify your add-ons yourself through entries below, set the package to "minimal"
# as otherwise your definition might be in conflict with what the installation package defines.
#
# Optional. If not set, the dashboard (https://<yourserver>:8080/) will ask you to choose a package.
#
# Valid options:
#   - minimal  : Installation only with dashboard, but no UIs or other add-ons. Use this for custom setups.
#   - simple   : Setup for using openHAB purely through UIs - you need to expect MANY constraints in functionality!
#   - standard : Default setup for normal users, best for textual setup
#   - expert   : Setup for expert users, especially for people migrating from openHAB 1.x
#   - demo     : A demo setup which includes UIs, a few bindings, config files etc.
#
# See https://www.openhab.org/docs/configuration/packages.html for a detailed explanation of these packages.
#
package = minimal

# Access Remote Add-on Repository
# Defines whether the remote openHAB add-on repository should be used for browsing and installing add-ons.
# This not only makes latest snapshots of add-ons available, it is also required for the installation of
# any legacy 1.x add-on. (default is true)
#
#remote = true

# Include legacy 1.x bindings. If set to true, it also allows the installation of 1.x bindings for which there is 
# already a 2.x version available (requires remote repo access, see above). (default is false)
#
#legacy = true

# A comma-separated list of bindings to install (e.g. "binding = sonos,knx,zwave")
#binding = astro,knx,novelanheatpump1,kostalinverter,onewire,squeezebox,weather1,http1
binding = astro,knx,novelanheatpump1,kostalinverter,onewire,weather1,http1

# A comma-separated list of UIs to install (e.g. "ui = basic,paper")
ui = basic,paper

# A comma-separated list of persistence services to install (e.g. "persistence = rrd4j,jpa")
persistence = rrd4j,jdbc-mysql,influxdb

# A comma-separated list of actions to install (e.g. "action = mail,pushover")
#action = 

# A comma-separated list of transformation services to install (e.g. "transformation = map,jsonpath")
transformation = javascript

# A comma-separated list of voice services to install (e.g. "voice = marytts,freetts")
#voice = 

# A comma-separated list of miscellaneous services to install (e.g. "misc = myopenhab")
misc = ruleengine
```

**Comment by wborn** [comment]
It's not really Docker specific but more a JFrog repository configuration problem:

> Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact mysql:mysql-connector-java:jar:8.0.13 in openhab (https://openhab.jfrog.io/openhab/libs-release/)

The issue seems to be that the https://openhab.jfrog.io/openhab/libs-release/ no longer contains all artifacts (only some). Perhaps @kaikreuzer did some reconfiguration while looking into https://github.com/openhab/openhab-distro/issues/1256?

**Comment by kaikreuzer** [comment]
@wborn You are right, I replaced JCenter by Maven Central, but it seems I made a misconfiguration there. Fixed it now and the artifact should now be available: https://openhab.jfrog.io/artifactory/libs-all/mysql/mysql-connector-java/8.0.13/mysql-connector-java-8.0.13.jar

@ccbur Could you please retest?

**Comment by ccbur** [comment]
Great! :-) It works now!! 

Thank you very much!

**Comment by ccbur** [comment]
Today I got the same exception again, but after another restart it was working correctly. @kaikreuzer Could there still be some misconfiguration in place?

**Comment by kaikreuzer** [comment]
As the link above (https://openhab.jfrog.io/artifactory/libs-all/mysql/mysql-connector-java/8.0.13/mysql-connector-java-8.0.13.jar) still works, I would say no.

**Comment by ccbur** [comment]
Yes the link works, but at least the certificate cannot be validated with the CAs in the docker image:

```
root@myopenhab-7f598d8bdc-rn5vf:/openhab# curl -vv https://openhab.jfrog.io/artifactory/libs-all/mysql/mysql-connector-java/8.0.13/mysql-connector-java-8.0.13.jar -o /dev/null
* Expire in 0 ms for 6 (transfer 0x4968a0)
* Expire in 1 ms for 1 (transfer 0x4968a0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Expire in 0 ms for 1 (transfer 0x4968a0)
* Expire in 2 ms for 1 (transfer 0x4968a0)
* Expire in 0 ms for 1 (transfer 0x4968a0)
* Expire in 0 ms for 1 (transfer 0x4968a0)
....
* Expire in 50 ms for 1 (transfer 0x4968a0)
* Expire in 50 ms for 1 (transfer 0x4968a0)
* Expire in 50 ms for 1 (transfer 0x4968a0)
*   Trying 35.190.146.4...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x4968a0)
* Connected to openhab.jfrog.io (35.190.146.4) port 443 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [112 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3706 bytes data]
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: self signed certificate in certificate chain
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I'm not really familiar with the karaf implementation, but what I figured out is that openhab is using _/openhab/userdata/etc/keystore_ and not the CAs from the system directly. I delete this file on every start and it is recreated, but too be honest I have no idea from where the CAs are imported. Are those the system CAs? If yes, then karaf will not be able to validate the server CA as this CA is missing in the docker images.

But no idea why it's working 90% of the time. Maybe my theory is bullshit... ;-)

**Comment by wborn** [comment]
It uses the certificates provided by the JVM (/usr/lib/jvm/default-jvm/lib/security/cacerts)

The artifacts are served by a CDN so it could be depending on your region and some server in the CDN may have certificate issues.

There could also be a man in the middle trying to inject something harmful in your downloads,  then the  certificates are protecting you and it is working as designed. :wink:
