### ISSUE TITLE
LibPCAP support for Amazon Dash Binding

### ISSUE THREAD

**Issue by 1activegeek** [openhab/openhab-docker#85]
It seems at this point that the Amazon Dash binding requires a separate install and permission settings to accommodate detecting Dash buttons. This requires install of libpcap drivers to sniff the wire. I know some folks may not configure Docker to allow this host to be able to sniff the wire, but if setup with a macvlan network or other customer configs, the adapter should be able to sniff the wire properly. 

I would like to see the extensibility of adding this setup to support the Dash binding to the core docker container, so that if I do this manually it won't be overwritten anytime an update is pushed to the image. Also in the case of testing with other setups, it would be useful to not need to reinstall. 

Reference Binding Installation: http://docs.openhab.org/addons/bindings/amazondashbutton/readme.html#prerequisites

**Comment by legacycode** [comment]
Hi, libpcap is alredy included in our docker image. You need to start the container as root and bind the interface to the host. You can find an example in the documentation at:

https://github.com/openhab/openhab-docker#running-openhab-with-libpcap-support

Let me know, if this solves your problem.

Best Regards.

**Comment by ChromoX** [comment]
I've tried everything in this thread, and another closed one. The buttons won't show up in the inbox. It seems to me that the Amazon Dash service is not even starting up. I've run the docker container as root, with the docker-compose file, etc... I get nothing. In my openhab.log I do see the DHCP requests when I push the Amazon Dash button, but I get no other indication they exist. I'm trying to run the armhf version on an Odroid-XU3.

**Comment by cniweb** [comment]
Can you try running OH2 directly on your Odroid-XU3? And then look, if the Amazon Dash button works?
Maybe it's not a docker image problem!

**Comment by zlokomatic** [comment]
Hi,

i also tried to get the Dash Button working with the docker image on the raspberry3 but it does not work.

The container is completely fresh and with libpcap support using the documentation and docker-compose

The error message i got is:

`2017-03-26 23:16:01.250 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while initializing handler of thing 'amazondashbutton:dashbutton:6e23f5f5': java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Pointer`

**Comment by wOvalle** [comment]
Hello,

I cannot set up a Dash Button with openhab 2.1 (running with in docker [as shown here](https://github.com/openhab/openhab-docker#running-openhab-with-libpcap-support)) running on my rpi3, Dash is not being recognized. I cannot see anything in the logs (I connected to the openhab client and typed `log:display`). Any ideas?

**Comment by andre161292** [comment]
Hi,

i have the same issue on my OpenHAB instance. I checked out the sources and played around with them a bit, trying to figure out the source of the error.
The first thing i noticed is, that no network interfaces have been found. So i digged deeper and added a logger to the catch-block of PcapUtil's getAllNetworkInterfaces method, which gave me the following:

        2017-09-18 12:54:08.166 [ERROR] [zondashbutton.internal.pcap.PcapUtil] - Cannot retrieve NetworkInterfaces
        org.pcap4j.core.PcapNativeException: Return code: -1, Message: Can't open netlink socket 13:Permission denied
                at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:58)[256:org.openhab.binding.amazondashbutton:2.2.0.201709181253]
                at org.openhab.binding.amazondashbutton.internal.pcap.PcapUtil.getAllNetworkInterfaces(PcapUtil.java:34)[256:org.openhab.binding.amazondashbutton:2.2.0.201709181253]
                at org.openhab.binding.amazondashbutton.internal.pcap.PcapNetworkInterfaceService.determineBoundNetworkInterfaces(PcapNetworkInterfaceService.java:181)[256:org.openhab.binding.amazondashbutton:2.2.0.201709181253]
                at org.openhab.binding.amazondashbutton.internal.pcap.PcapNetworkInterfaceService.access$2(PcapNetworkInterfaceService.java:179)[256:org.openhab.binding.amazondashbutton:2.2.0.201709181253]
                at org.openhab.binding.amazondashbutton.internal.pcap.PcapNetworkInterfaceService$1.run(PcapNetworkInterfaceService.java:62)[256:org.openhab.binding.amazondashbutton:2.2.0.201709181253]
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_144]
                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_144]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_144]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_144]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_144]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_144]
                at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]

To me, it seems like some flag has been forgotten to set or docker is corrupt. I'm using docker 1.13.1 and used a slightly modified version of the docker-compose.yml that includes NET_ADMIN and NET_RAW, offered at dockerhub.

Does someone know how to fix this?

**Comment by cniweb** [comment]
Is your problem still there or can we close this issue?

**Comment by andre161292** [comment]
I'll check this out later and will let you know. Haven't tried it for a while now.

**Comment by FlorianSW** [comment]
So, I've tried it out with the alpine 2.2.0 image, starting the container and running openhab inside with root works pretty fine, so there shouldn't be any change needed to the Dockerfile, except someone finds out how to to use it with a non-root user (all my attempts unfortunately failed).

**Comment by cniweb** [comment]
Perhaps the containers lacking any Linux capabilities:
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
