### ISSUE TITLE
karaf can't create userdata/tmp when using a different USER_ID

### ISSUE THREAD

**Issue by idlethread** [openhab/openhab-docker#88]
```
export NEW_USER_ID=`id -u openhab`

$ docker run \
        --restart=always \
        --name openhab \
        -d \
        -e USER_ID=$NEW_USER_ID \
        --net=host \
        -p $HTTP_PORT:8080 \
        -p $HTTPS_PORT:8143 \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -v /opt/openhab/addons:/openhab/addons \
        -v /opt/openhab/conf:/openhab/conf \
        -v /opt/config/openhab/userdata:/openhab/userdata \
        openhab/openhab:2.0.0-amd64
$ docker logs openhab
```
Launching the openHAB runtime...
java.lang.RuntimeException: Exception instantiating lock class org.apache.karaf.main.lock.SimpleFileLock
Could not create file lock: Invalid karaf.lock.dir system property '/openhab/userdata/tmp' : does not exist
        at org.apache.karaf.main.Main.createLock(Main.java:443)
        at org.apache.karaf.main.Main.doMonitor(Main.java:371)
        at org.apache.karaf.main.Main.access$100(Main.java:72)
        at org.apache.karaf.main.Main$2.run(Main.java:362)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.karaf.main.Main.createLock(Main.java:439)
        ... 3 more
Caused by: java.lang.RuntimeException: Could not create file lock: Invalid karaf.lock.dir system property '/openhab/userdata/tmp' : does not exist
        at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:58)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Invalid karaf.lock.dir system property '/openhab/userdata/tmp' : does not exist
        at org.apache.karaf.main.lock.SimpleFileLock.validateDirectoryExists(SimpleFileLock.java:117)
        at org.apache.karaf.main.lock.SimpleFileLock.getKarafLock(SimpleFileLock.java:93)
        at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:46)
        ... 8 more

**Comment by cniweb** [comment]
Do you still have the problem?

**Comment by cniweb** [comment]
@idlethread Can I close this issue?

**Comment by idlethread** [comment]
I can't seem to reproduce it anymore. This can be closed, thanks.
